project_id = "ghxfcasnlkgjefkogoio"

[functions.fx-rates]
verify_jwt = false

[functions.fx-swap]
verify_jwt = false

[functions.fx-anchor-info]
verify_jwt = false

[functions.fx-anchor-scan]
verify_jwt = false

[functions.fx-anchor-debug]
verify_jwt = false