project_id = "ghxfcasnlkgjefkogoio"

[functions.fx-rates]
verify_jwt = false

[functions.fx-swap]
verify_jwt = false

[functions.fx-build-swap]
verify_jwt = false

[functions.fx-publish-swap]
verify_jwt = false

[functions.fx-anchor-info]
verify_jwt = false

[functions.fx-anchor-scan]
verify_jwt = false

[functions.fx-anchor-debug]
verify_jwt = false

[functions.fx-market-data]
verify_jwt = false

[functions.fx-record-price]
verify_jwt = false

[functions.fx-keeta-proxy]
verify_jwt = false

[functions.fx-list-nft]
verify_jwt = false

[functions.fx-buy-nft]
verify_jwt = false

[functions.fx-upload-collection]
verify_jwt = false

[functions.fx-get-collection]
verify_jwt = false

[functions.fx-batch-upload]
verify_jwt = false

[functions.fx-update-collection]
verify_jwt = false

[functions.fx-cancel-listing]
verify_jwt = false

[functions.fx-recover-nft]
verify_jwt = false

[functions.fx-recover-listings]
verify_jwt = false
